### PR TITLE
Odst 237 remove unused resolvers servicers

### PR DESCRIPTION
**Pull request by ericcater**
## Description

Removed unused functions in servicer/resolver. No code code/content changes, but need to make sure something that is needed wasn't removed.

## Checklist:

- [x] I have performed a self-review of my code to ensure that unintended code is not introduced.
- [x] I have commented my code, particularly in hard-to-understand areas to ensure that the next group of developers can understand my code.
- [x] I have added tests that prove my fix/feature functions so that future modifications to the code do not break my additions.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue, example: swapping the order of numbers on a UI)
- [ ] New feature (non-breaking change which adds functionality, new page on the frontend)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected, example: API change that requires dependent projects to be updated)
- [ ] This change requires a documentation update (example: new setup instructions for a new feature)

## How Has This Been Tested?

Describe the tests that you created to tests your changes. Use N/A if no tests were created.

N/A (Though I and the reviewer need to make sure I didn't delete a test of something that is still used).

### CODE REVIEW

**Review by Mikehickey7 — APPROVED** [review]

**Review by Mikehickey7 — APPROVED** [review]

**Comment by yurisim** [comment]
Don't merge yet

**Review by BrendenMcGrew — APPROVED** [review]

**Review by pmeskridge — APPROVED** [review]
Approved but the Tag module, repo, resolver and service may need to be put back.

**Review by yurisim — CHANGES_REQUESTED** [review]
Right now frontend is fetching a static array of tags instead of querying the backend. 

image

Still need the tag module, undelete it and remind @pmeskridge  to reimplement the correct way.

Really surprised @BrendenMcGrew didn't point this out in his review....

**Comment by BrendenMcGrew** [comment]
I did. And I'm fixing it in my branch. It's also midnight rn.

I asked to not have those files deleted to which I was told I could just overwrite it in my pull request.

**Comment by yurisim** [comment]
> I did. And I'm fixing it in my branch. It's also midnight rn.
> 
> I asked to not have those files deleted to which I was told I could just overwrite it in my pull request.

You don't need to be responding to this @ midnight. :P

In the future, please make a quick note in the PR that y'all have spaghetti arrangements like this.

Also, you don't "overwrite it in your pull request", what will probably happen is that this will be extra files to resolve in a merge conflict on your branch once this gets into dev. You were complaining about merge conflicts earlier this week, not undeleting it here will add to the conflicts.

**Review by yurisim — APPROVED** [review]

**Comment by yurisim** [comment]
Revised wording on feedback questions and adjusted corresponding questions in back end

**Pull request merged**
